version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
  browser: circleci/browser-tools@1.2.4
filters:
  branches:
    only:
      - main     
jobs:
  deploy:
    docker:
      - image: "cimg/base:stable"
        environment:
          NODE_ENV: development
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - browser/install-chrome
      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python3-dev build-essential
            sudo pip3 install awsebcli
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build   
      - run:
          name: Install puppeteer
          command: |
            npm i puppeteer --dev -save
      - run:   
          name: test
          command: |
            npm run test      
      - run:
          name: Deploy frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy backend
          command: |
            npm run backend:deploy
            
workflows:
  build:
    jobs:
      - deploy:
          filters:
            branches:
              only:
              - main